### ISSUE TITLE
Workaround setup ladspa in azuracast

### ISSUE THREAD

**Issue by houtjetouwtje** [mkpascal/mk_liquidsoap_processing#3]
Hello all,

got an update from Buster Neece.
Ladspa is now supported in azuracast.
But i can‘t get in running.
How do i activate the plugins in azuracast?
Got the updated dockerfile from the rolling release channel, en copied pascal script in liquidsoap config.
No errors, but also no processing...
Need some help.
Thanks in advance

**Comment by radioguy0** [comment]
Hey there, the primary dev of AzuraCast has written this file linked below which automatically works when inserted on the Edit LiquidSoap configuration page under Utilities (paste it into the second last open box for editing). 

You then have to restart your stream and it should work automatically.

You would have to manually adjust the numbers yourself to make it sound the way you want, but this preset might suit your needs for now.

https://gist.github.com/SlvrEagle23/43a06ee6624975273fdc903ba4a39998

**Comment by houtjetouwtje** [comment]
Got it working!
Hudge improvement.
Thanks for all the help👍
