### ISSUE TITLE
Sky radio sound

### ISSUE THREAD

**Issue by eranwo** [mkpascal/mk_liquidsoap_processing#4]
@mkpascal 
Thank you fo the greate code !!
could you change the parameters in order to get sound like in **SKY RADIO** ?
https://22713.live.streamtheworld.com/SKYRADIO.mp3

**Comment by mkpascal** [comment]
This is not possible with this solution, sorry. I'm only using ladspa plugins which provides a good enough radio streaming sound but nothing close to professional broadcast audio processing.

You should try StereoTool if you want to get a more processed sound. You'll get closer to the sound you're trying to get with this software. It'll also work with liquidsoap using the pipe method.
