### ISSUE TITLE
Error 3: Syntax error!

### ISSUE THREAD

**Issue by mailinglists35** [mkpascal/mk_liquidsoap_processing#7]
````
$ liquidsoap -c process.liq
At process.liq, line 8, char 34-36:
def multiband_band(process, from, to, attack, release, ratio, threshold, gain)

Error 3: Syntax error!
````

char 34-36 corresponds to "to" field and is highlighted in red in output
using it on ubuntu 22.04lts

````
$ dpkg -l |grep liquid
ii  liquidsoap                           2.0.2-1build2                           amd64        audio streaming language
````

**Comment by mkpascal** [comment]
This needs to be integrated as part of a bigger Liquidsoap script.

Would you be able to give me an example of how you're running it? (removing any sensitive data if necessary)

**Comment by mkpascal** [comment]
I'm assuming this is fixed since there's no answer. Closing! Feel free to reopen if there's still an issue.
